export const ADMIN_ROUTE = '/admin'
export const AUTH_ROUTE = '/auth'
export const REGISTRATION_ROUTE = '/registration'
export const BASKET_ROUTE = '/basket'
export const DEVISE_ROUTE = '/device'
export const SHOP_ROUTE = '/'
